### ISSUE TITLE
NOPackagesFoundError

### ISSUE THREAD

**Issue by megreichel** [juskaiser/FARCON_NLP#1]
Hi - I'm trying to go through all steps to be prepared for FARCON training.  I was able to complete Step 2 Clone the Training Repository.  But when running Step 3 Create your Local Environment, I attempt:
 
In command line, from within the FARCON_NLP folder, run the following command:
conda env create -f environment.yml

And I get the error:
NoPackagesFoundError: Package missing in current win-64 channels:  
- appnope 0.1.0 py36__0

I had to move everything from the FARCON_NLP folder into the Miniconda3\Scripts folder just so that the objects in FARCON_NLP folder could be seen by conda and so I'm running the "conda env create -f environment.yml" command from there.

**Comment by juskaiser** [comment]
@megreichel Thanks for reporting this and for the detailed response. I modified the environment file so that the environment doesn't require specific dependencies, only the main libraries we will be using. This should allow flexibility across different OS's. Can you try building your environment with the updated environment file and see how it goes?

**Comment by megreichel** [comment]
I got past this - thanks!  Now I got stuck with the jupyter notebook not opening completely.  Please see the issue - thanks!
